Rayhan Christian Wewengkang. 2024081005. Tugas 6

In [5]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder

In [6]:
#data tugas
data = {
    'Harga': ['Murah', 'Murah', 'Sedang', 'Mahal', 'Mahal', 'Sedang', 'Sedang', 'Mahal'],
    'Diskon': ['Ada', 'Ada', 'Ada', 'Tidak Ada', 'Tidak Ada', 'Ada', 'Tidak Ada', 'Ada'],
    'Ulasan': ['Baik', 'Baik', 'Baik', 'Buruk', 'Buruk', 'Baik', 'Baik', 'Buruk'],
    'Hasil': ['Tertarik', 'Tertarik', 'Tertarik', 'Tidak Tertarik', 'Tidak Tertarik', 'Tertarik', 'Tertarik', 'Tidak Tertarik']
}

df = pd.DataFrame(data)
print("Data Latih:")
display(df)

Data Latih:


,Harga,Diskon,Ulasan,Hasil
0,Murah,Ada,Baik,Tertarik
1,Murah,Ada,Baik,Tertarik
2,Sedang,Ada,Baik,Tertarik
3,Mahal,Tidak Ada,Buruk,Tidak Tertarik
4,Mahal,Tidak Ada,Buruk,Tidak Tertarik
5,Sedang,Ada,Baik,Tertarik
6,Sedang,Tidak Ada,Baik,Tertarik
7,Mahal,Ada,Buruk,Tidak Tertarik


Pra-pemrosessan Data (Encoding)

In [7]:
# Memisahkan fitur (X) dan target (y)
X = df[['Harga', 'Diskon', 'Ulasan']]
y = df['Hasil']

# Inisialisasi encoder
encoder = OrdinalEncoder()

# Fit dan transform data fitur menjadi numerik
X_encoded = encoder.fit_transform(X)

print("\nRepresentasi Numerik dari Fitur (X):")
print(X_encoded)


Representasi Numerik dari Fitur (X):
[[1. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [2. 0. 0.]
 [2. 1. 0.]
 [0. 0. 1.]]


Model Training

In [8]:
# Inisialisasi model Naive Bayes Kategorikal dengan Laplace Smoothing
# alpha=1.0 akan menambahkan 1 ke setiap frekuensi fitur untuk mencegah probabilitas 0
model = CategoricalNB(alpha=1.0)

# Melatih model dengan data numerik
model.fit(X_encoded, y)

print("Model Categorical Naive Bayes berhasil dilatih.")

Model Categorical Naive Bayes berhasil dilatih.


Prediksi Data Baru

In [9]:
# Mendefinisikan data baru
new_data = pd.DataFrame([['Sedang', 'Ada', 'Baik']], columns=['Harga', 'Diskon', 'Ulasan'])

new_data_encoded = encoder.transform(new_data)

# Memprediksi kelas (Hasil)
prediksi_kelas = model.predict(new_data_encoded)

# Melihat probabilitas dari masing-masing kelas
probabilitas = model.predict_proba(new_data_encoded)

print(f"Data Pelanggan Baru: Harga={new_data.iloc[0]['Harga']}, Diskon={new_data.iloc[0]['Diskon']}, Ulasan={new_data.iloc[0]['Ulasan']}")
print(f"\n>> PREDIKSI HASIL: {prediksi_kelas[0]} <<")

# Menampilkan probabilitas di balik layar
kelas_target = model.classes_
print("\nProbabilitas Posterior (Setelah Smoothing dan Normalisasi):")
for i, kelas in enumerate(kelas_target):
    # Mengalikan dengan 100 untuk format persentase
    print(f"- {kelas}: {probabilitas[0][i] * 100:.2f}%")

Data Pelanggan Baru: Harga=Sedang, Diskon=Ada, Ulasan=Baik

>> PREDIKSI HASIL: Tertarik <<

Probabilitas Posterior (Setelah Smoothing dan Normalisasi):
- Tertarik: 97.45%
- Tidak Tertarik: 2.55%
